import { useState, useRef } from 'react';
import { SendHorizonal } from 'lucide-react';

export default function ChatInputBar({ onSend, disabled }) {
  const [text, setText] = useState('');
  const ref = useRef(null);

  const resize = () => {
    if (ref.current) {
      ref.current.style.height = 'auto';
      ref.current.style.height = Math.min(ref.current.scrollHeight, 120) + 'px';
    }
  };

  const submit = () => {
    if (text.trim() && !disabled) {
      onSend(text.trim());
      setText('');
      if (ref.current) ref.current.style.height = 'auto';
    }
  };

  return (
    <div className="chat-input-area">
      <div className="chat-input-wrapper">
        <textarea
          ref={ref}
          className="chat-input-textarea"
          placeholder="Ask about life, duty, or purpose..."
          rows={1}
          value={text}
          onChange={e => { setText(e.target.value); resize(); }}
          onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submit(); } }}
          disabled={disabled}
        />
        <button className="chat-send-btn" onClick={submit} disabled={disabled || !text.trim()}>
          <SendHorizonal size={20} />
        </button>
      </div>
      <p className="chat-disclaimer">Responses generated by AI based on the Bhagavad Gita.</p>
    </div>
  );
}
